<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>ShadowMaiden</RootNamespace>
    <StartupObject>ShadowMaiden.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Levels\*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
